### PR TITLE
addons

### PR DESCRIPTION
**Pull request by IshwaranRudhara**

### CODE REVIEW

**Comment by anburocky3** [comment]
@IshwaranRudhara Have you resolved the code changes?

**Comment by IshwaranRudhara** [comment]
thala onnum purila thala, neegale matirugah

**Comment by yogesh7401** [comment]
@anburocky3 I resolved the conflict and it is ready to merge

**Comment by anburocky3** [comment]
I don't see any commits from you @yogesh7401

**Comment by anburocky3** [comment]
Merged. Thank you for your contributions. @IshwaranRudhara @yogesh7401

**Pull request merged**
